# Generated by Django 5.2.6 on 2025-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الرمز')),
                ('limit', models.PositiveIntegerField(default=20, verbose_name='عدد الشهادات المسموح بها')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='المستخدم منها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
