# Generated by Django 5.2.6 on 2025-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القالب')),
                ('background', models.ImageField(upload_to='certificates/', verbose_name='الخلفية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
