# Generated by Django 5.2.6 on 2025-11-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'تصنيف الشهادات',
                'verbose_name_plural': 'تصنيفات الشهادات',
            },
        ),
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'verbose_name': 'قالب شهادة', 'verbose_name_plural': 'قوالب الشهادات'},
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='background',
            field=models.ImageField(upload_to='certificates/', verbose_name='صورة الخلفية'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان القالب'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='certificates.certificatecategory', verbose_name='التصنيف'),
        ),
    ]
