"""
Django settings for shahadht project (Ready for Railway Deployment)
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
import dj_database_url  # لدعم قاعدة بيانات Railway

# ------------------------------
# 🏗️ المسار الرئيسي
# ------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------
# 🔐 المفاتيح والأمان
# ------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-$*k3su#@_elq#y13ym1l1%(f@s830%_q5gs7u4g2)4g)#!_p(8')
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = ["*"]

# ------------------------------
# 📦 التطبيقات
# ------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # التطبيقات الخاصة بك
    'core',
    'certificates',
    'commerce',
]

# ------------------------------
# ⚙️ Middleware
# ------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # لتفعيل WhiteNoise للملفات الثابتة
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------
# 🔗 URL الرئيسي
# ------------------------------
ROOT_URLCONF = 'shahadht.urls'

# ------------------------------
# 🧱 القوالب
# ------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shahadht.wsgi.application'

# ------------------------------
# 🗄️ قاعدة البيانات
# ------------------------------
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# ------------------------------
# 🔒 التحقق من كلمات المرور
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------
# 🌍 اللغة والتوقيت
# ------------------------------
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_TZ = True

# ------------------------------
# 🧩 ملفات STATIC و MEDIA
# ------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# استخدام التخزين عبر WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ------------------------------
# 🆔 الإعداد الافتراضي للمفاتيح
# ------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
